---

galaxy_info:
  author: Dennis Tait, Jiri Tyr
  description: A role that installs Artifactory
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - web
    - db
dependencies:
  - config_encoder_filters
